### ISSUE TITLE
crash under situation when "dest: " or "origin: "

### ISSUE THREAD

**Issue by joejztang** [joejztang/hexo-undraft#1]
when placeholders have "dest" and/or "origin" and leave blank after, application will crash.

_drafts/add-binary.md null
Error:  TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at /Users/xxx/Documents/TechBlog/node_modules/hexo-undraft/lib/undraft.js:82:50
    at Model._Query.Query.Query.map (/Users/xxx/Documents/TechBlog/node_modules/warehouse/lib/query.js:229:17)
    at /Users/xxx/Documents/TechBlog/node_modules/hexo-undraft/lib/undraft.js:79:30
    at Promise._execute (/Users/xxx/Documents/TechBlog/node_modules/hexo-undraft/node_modules/bluebird/js/release/debuggability.js:159:9)
    at Promise._resolveFromExecutor (/Users/xxx/Documents/TechBlog/node_modules/hexo-undraft/node_modules/bluebird/js/release/promise.js:460:18)
    at new Promise (/Users/xxx/Documents/TechBlog/node_modules/hexo-undraft/node_modules/bluebird/js/release/promise.js:76:14)
    at selectPost (/Users/xxx/Documents/TechBlog/node_modules/hexo-undraft/lib/undraft.js:64:14)
    at tryCatcher (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/xxx/Documents/TechBlog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by joejztang** [comment]
when have both `dest:` and `origin:` and execute `hexo undraft -a`

**Comment by joejztang** [comment]
solved.
